### ISSUE TITLE
能否添加多个账号执行Action呢？

### ISSUE THREAD

**Issue by PennHui666** [RayWangQvQ/BiliBiliTool#53]
感谢作者慷慨分享好用的工具，问题如标题。通过添加其他账号的DEDEUSERID、SESSDATA、BILI_JCT值能否实现？

**Comment by Mmx233** [comment]
用服务器或本地运行可以实现多开

**Comment by Mmx233** [comment]
fork项目后bilibili-daily-task.yml修改启动参数应该也行，但好像会出现冲突

**Comment by frendguo** [comment]
添加一个 DEDEUSERID2 ......

然后再修改下 bilibili-daily-task.yml 
```yaml
- name: Run
      env:
        userId: ${{secrets.USERID}}
        sessData: ${{secrets.SESSDATA}}
        biliJct: ${{secrets.BILIJCT}}
        otherConfigs: ${{secrets.OTHERCONFIGS}}
        userId2: ${{secrets.USERID2}}
        sessData2: ${{secrets.SESSDATA2}}
        biliJct2: ${{secrets.BILIJCT2}}
        otherConfigs2: ${{secrets.OTHERCONFIGS2}}
      run: 
        dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
       dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId2} -sessData=${sessData2} -biliJct=${biliJct2} -closeConsoleWhenEnd=1 ${otherConfigs2}
```

理论上应该可以的。
