### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid because: Unsupported config option for services: 'bilibili_tool'

### ISSUE THREAD

**Issue by Tongmengjun** [RayWangQvQ/BiliBiliTool#538]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'bilibili_tool'

**Comment by RayWangQvQ** [comment]
You could try add the `version` keyword before the `services` keyword in the `docker-compose.yml` file.

Such as:

```
version: "3.7"
services:
  bilibili_tool:
    image: zai7lou/bilibili_tool
    container_name: bilibili_tool
    restart: always
    volumes:
      - ./Logs:/app/Logs
      - ./my_crontab:/app/custom_crontab
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
```
