### ISSUE TITLE
【建议】支持 GitHub Actions 部署腾讯云函数

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliTool#574]
建议内容：
支持 GitHub Actions 部署腾讯云函数

**Comment by catlair** [comment]
希望 serverless 的运行时时间和地区能直接在 secrets 中配置：

`serverless.yml`中使用env的方式

```yaml
#组件参数配置
inputs:
  name: ${name}_scf # 云函数名称，默认为 ${name}-${stage}-${app}
  region: ${env:REGION} # 函数所在区域
  events: #触发器
    - timer: #签到
        parameters:
          cronExpression: ${env:CRON_EXP}
          enable: true
```

**Comment by catlair** [comment]
如果可以，可以让我写这个

**Comment by catlair** [comment]
action 不用npm install

```yaml
    steps:
      - name: clone local repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: install serverless
        run: npm install -g serverless

      - name: deploy serverless
        run: |
          cd ./tencentScf
          chmod +x publish.sh
          ./publish.sh
          sls deploy --debug
        env: # 环境变量
          STAGE: dev #您的部署环境
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless海外默认为aws部署，配置为腾讯部署
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号sercret ID
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号sercret key
          SCF_REGION: ${{ secrets.SCF_REGION || 'ap-guangzhou' }}

```

**Comment by RayWangQvQ** [comment]
@catlair 好的，那你来吧，我来 Assign 给你~

**Comment by catlair** [comment]
> > 如果可以，可以让我写这个
> 
> @catlair 可以啊，那你来吧，我来 Assign 给你~

看到你完成的差不多了，我删了这一条啊，怎么还能看到😂

**Comment by RayWangQvQ** [comment]
可能当时我的浏览器没有刷新，现在看不到了😂

那你还要写不？

**Comment by catlair** [comment]
> 可能当时我的浏览器没有刷新，现在看不到了😂
> 
> 那你还要写不？

@RayWangQvQ 就差一个文档了吧，你在写了吗，我今天没时间了

**Comment by RayWangQvQ** [comment]
还剩下你提到的**触发器问题**和**环境变量**问题还没有解决。

现在是每次 deploy ，触发器和环境变量都会根据 serverless.yml 里的去重置，而不是累加的。也就是在部署后，如果自己又在函数控制台修改了配置（触发器或环境变量），那它们在执行部署后都会被覆盖掉，这个显然不是大家想要的。

如果想不覆盖的话，那就要求所有都只通过 Secrets 来配置，而不是去操作控制台（但这样做其实有点恶心，也反常识）。

我在想是不是用 sls deploy 并不是最好的方案，或许用 sdk 提供的接口可以实现不修改函数控制台已有配置的部署？

**Comment by catlair** [comment]
> 如果想不覆盖的话，那就要求所有都只通过 Secrets 来配置，而不是去操作控制台（但这样做其实有点恶心，也反常识）。
> 
> 我在想是不是用 sls deploy 并不是最好的方案，或许用 sdk 提供的接口可以实现不修改函数控制台已有配置的部署？

@RayWangQvQ 环境变量确实麻烦，如果考虑不同的环境部署到scf配置的方式会有点不同。

**Comment by catlair** [comment]
@RayWangQvQ 
我不会 C# 也不是很清楚😂
整个 secret 写肯能会存在特殊字符的问题，之前我是用的转换后的填入

https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions

```yaml
- name: Do Something with env files
  env:
    QA_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
    PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
  run: |
    [ "$YOUR_ENVIRONMENT" = qa ] && echo $QA_ENV_FILE | base64 --decode > .env
    [ "$YOUR_ENVIRONMENT" = prod ] && echo $PROD_ENV_FILE | base64 --decode > .env
```

不知 C# 能不能直接加载 .env 到环境变量
